package enums;

public enum MainActions {
    SHOW_NAVIGATION,
    SHOW_SHARE_INFORMATION,
    SHOW_SHARE_TRADES,
    SHOW_BROKERS,
    SHOW_BROKER_TRADES,
    SHOW_SHAREHOLDERS,
    SHOW_SHAREHOLDERS_OF_SHARE,
    EXIT_APPLICATION
}
